---
- hosts: all
  vars:
    docker_registry_username: "{{ lookup('env','github.actor') }}"
    docker_registry_password: "{{ lookup('env','secrets.GITHUB_TOKEN') }}"
    docker_registry_url: "ghcr.io"
    docker_network_name: "proxy_net"
    env_var1: "{{ lookup('env','ENV_VAR1') }}"

  tasks:
  - name: Login to Docker Registry
    docker_login:
      username: "{{ docker_registry_username }}"
      password: "{{ docker_registry_password }}"
      registry: "{{ docker_registry_url }}"

  - name: Deploy Docker container
    docker_container:
      name: your_container_name
      image: your_docker_image
      networks:
        - name: "{{ docker_network_name }}"
      restart: unless-stopped
      env:
        MYSQL_USER: "{{ mysql_user }}"
        MYSQL_PASSWD: "{{ mysql_passwd }}"
        MYSQL_HOST: "{{ mysql_host }}"
        MYSQL_PORT: "{{ mysql_PORT }}"
        MYSQL_DB_NAME: "{{ mysql_db_name }}"
