---
- hosts: all
  become: true
  tasks:
  - name: Login to Docker Registry
    docker_login:
      username: "{{ docker_registry_username }}"
      password: "{{ docker_registry_password }}"
      registry: "{{ docker_registry_url }}"

  - name: Deploy Docker container
    docker_container:
      name: webhook_spaceway_lora
      image: ghcr.io/aircentre/webhook-spaceway-lora
      networks:
        - name: "{{ docker_network_name }}"
      restart_policy: unless-stopped
      state: started
      pull: yes
      env:
        MYSQL_USER: "{{ mysql_user }}"
        MYSQL_PASSWD: "{{ mysql_passwd }}"
        MYSQL_HOST: "{{ mysql_host }}"
        MYSQL_PORT: "{{ mysql_port }}"
        MYSQL_DB_NAME: "{{ mysql_db_name }}"
