---
- hosts: all
  vars:
    docker_registry_username: "{{ lookup('env','github.actor') }}"
    docker_registry_password: "{{ lookup('env','secrets.GITHUB_TOKEN') }}"
    docker_registry_url: "ghcr.io"
    docker_network_name: "proxy_net"
    mysql_user: "{{ lookup('env','secrets.MYSQL_DO_USERNAME') }}"
    mysql_passwd: "{{ lookup('env','secrets.MYSQL_DO_PW') }}"
    mysql_host: "{{ lookup('env','secrets.MYSQL_DO_HOST') }}"
    mysql_port: "{{ lookup('env','secrets.MYSQL_DO_PORT') }}"
    mysql_db_name: "{{ lookup('env','secrets.MYSQL_DO_DATABASE') }}"

  tasks:
  - name: Login to Docker Registry
    docker_login:
      username: "{{ docker_registry_username }}"
      password: "{{ docker_registry_password }}"
      registry: "{{ docker_registry_url }}"

  - name: Deploy Docker container
    docker_container:
      name: webhook-spaceway-lora
      image: ghcr.io/aircentre/webhook-spaceway-lora
      networks:
        - name: "{{ docker_network_name }}"
      restart: unless-stopped
      env:
        MYSQL_USER: "{{ mysql_user }}"
        MYSQL_PASSWD: "{{ mysql_passwd }}"
        MYSQL_HOST: "{{ mysql_host }}"
        MYSQL_PORT: "{{ mysql_PORT }}"
        MYSQL_DB_NAME: "{{ mysql_db_name }}"
