version: "3.9"
services:
  test-db:
    image: mysql:8.0
    command: |
      --default-authentication-plugin=mysql_native_password 
      --ssl=on 
      --ssl-ca=/etc/mysql/ssl/ca.crt 
      --ssl-cert=/etc/mysql/ssl/server.crt 
      --ssl-key=/etc/mysql/ssl/server.key
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ${PWD}/e2e/test_db/tls:/etc/mysql/ssl
      - ${PWD}/e2e/test_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 3306:3306
      
  webhook-spaceway-lora:
    build: .
    image: ghcr.io/aircentre/webhook-spaceway-lora
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWD: mysecretpassword
      MYSQL_HOST: test-db
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: Vessel_location
      ACCESS_KEY: test