name: CI workflow for webhook-spaceway-lora

on:
  push:
    branches:
      - main

jobs:
  build_test_push:
    name: Build, Test, and Push
    runs-on: ubuntu-latest
    # 'no-ci' in commit message skips job execution
    if: ${{ !contains(github.event.head_commit.message, 'no-ci') }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Authenticate with Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Go Environment
        uses: actions/setup-go@v3
        with: 
          go-version: '^1.20.2'

      - name: Cache Go Dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Execute Unit Tests
        run: go test ./internal/...
      
      - name: Setup End-to-End Environment
        run: |
          docker-compose up -d --build
          docker-compose exec -T test-db sh -c 'while ! mysqladmin ping -h0.0.0.0 --silent; do sleep 1; done'

      - name: Execute End-to-End Tests
        run: go test ./e2e/tests/...
      
      - name: Taredown End-to-End Environment
        run: docker-compose down -v

      - name: Push Docker Image to Registry
        run: docker compose push webhook-spaceway-lora

  deploy:
      needs: build_test_push
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Set up dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ansible
        
        - name: setup depoyment credentials
          run: |
            echo '${{ secrets.SERVER_PRIV_KEY }}' > priv_key
            chmod 600 priv_key
            echo '${{ secrets.SERVER_INV }}' > inventory

        - name: Run Ansible playbook
          # env:
          #   # MY_SECRET: ${{ secrets.YOUR_SECRET_NAME }}
          #   MYSQL_USER: ${{ secrets.MYSQL_DO_USERNAME }}
          #   MYSQL_PASSWD: ${{ secrets.MYSQL_DO_PW }}
          #   MYSQL_HOST: ${{ secrets.MYSQL_DO_HOST }}
          #   MYSQL_PORT: ${{ secrets.MYSQL_DO_PORT }}
          #   MYSQL_DB_NAME: ${{ secrets.MYSQL_DO_DATABASE }}
          # run: ansible-playbook -e "my_secret=$MY_SECRET" deploy.yml
          run: ansible-playbook -i inventory deploy.yml